version: "3.8"
services:

    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        expose:
            - "2181"
        ports:
            - 2181:2181
        volumes:
            - kafka_zookeeper:/opt/zookeeper-3.4.13/data
        networks:
            - kafkanet

    kafka1:
        image: wurstmeister/kafka:2.12-2.2.0
        container_name: kafka1
        command: [start-kafka.sh]
        expose:
            - "9092"
        ports:
            - 9092:9092
        environment:
        #      KAFKA_ADVERTISED_HOST_NAME: 172.25.0.12
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ADVERTISED_HOST_NAME: kafka1
            KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:19092
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://0.0.0.0:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_OPTS: -javaagent:/prometheus/jmx_prometheus_javaagent-0.15.0.jar=8080:/prometheus/kafka-2_0_0.yml
        volumes:
            - ./kafka/prometheus:/prometheus
            - kafka_kafka1:/opt/kafka_2.12-2.2.0/logs
        depends_on:
            - "zookeeper"
        networks:
            - kafkanet

    kafka2:
        image: wurstmeister/kafka:2.12-2.2.0
        container_name: kafka2
        command: [start-kafka.sh]
        expose:
            - "9093"
        ports:
            - 9093:9092
        environment:
            #      KAFKA_ADVERTISED_HOST_NAME: 172.25.0.13
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_HOST_NAME: kafka2
            KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://localhost:19093
            KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://0.0.0.0:19093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_OPTS: -javaagent:/prometheus/jmx_prometheus_javaagent-0.15.0.jar=8080:/prometheus/kafka-2_0_0.yml
        volumes:
            - ./kafka/prometheus:/prometheus
            - kafka_kafka2:/opt/kafka_2.12-2.2.0/logs
        depends_on:
            - "zookeeper"
        networks:
            - kafkanet


    jupyterlab:
        image: mrussorb/cluster-jupyterlab:3.0.14
        container_name: jupyterlab
        ports:
            - 8888:8888
        volumes:
            - shared-workspace:/opt/workspace
        networks:
           - sparknet

    spark-master:
        image: mrussorb/cluster-spark-master:3.1.1-hadoop3.2-v1.1.0      
        container_name: spark-master
        expose:
            - "7077"
            - "8080"
            - "4040"
            - "10000"
            - "10001"
        ports:
            - 7077:7077
            - 8080:8080
            - 4040:4040
            - 10000:10000
            - 10001:10001
        volumes:
            - shared-workspace:/opt/workspace
        networks: 
            - sparknet
                
            
    spark-worker-1:
        image: mrussorb/cluster-spark-worker:3.1.1-hadoop3.2-v1.1.0
        container_name: spark-worker-1
        environment:
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=512m
        ports:
            - 8081:8081
        volumes:
            - shared-workspace:/opt/workspace
        depends_on:
            - spark-master
        networks:
            - sparknet

    spark-worker-2:
        image: mrussorb/cluster-spark-worker:3.1.1-hadoop3.2-v1.1.0
        container_name: spark-worker-2
        environment:
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=512m
        ports:
            - 8082:8081
        volumes:
            - shared-workspace:/opt/workspace
        depends_on:
            - spark-master
        networks: 
            - sparknet

    spark-worker-3:
        image: mrussorb/cluster-spark-worker:3.1.1-hadoop3.2-v1.1.0
        container_name: spark-worker-3
        environment:
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=512m
        ports:
            - 8083:8081
        volumes:
            - shared-workspace:/opt/workspace
        depends_on:
            - spark-master
        networks: 
            - sparknet