## VERSION 1.1.0 DOCKER-COMPOSE 
version: "3.8"
services:


    jupyterlab:
        image: mrussorb/cluster-jupyterlab:${JUPYTERLAB_TAG_VERSION}
        container_name: jupyterlab
        ports:
            - 8888:8888
            - 4040:4040
        volumes:
            - shared-workspace:/opt/workspace
            - ./workspace:/opt/workspace/PROJECT
        networks:
            - sparknet
            - kafkanet
            - mongodbnet


    zeppelin:
        image: apache/zeppelin:0.8.1
        hostname: zeppelin
        container_name: zeppelin
        expose:
            - "7081"
        ports:
            - "7081:8080"
        volumes:
            - ./zeppelin/datadrive:/datadrive
            - ./zeppelin/pyspark-notebooks:/zeppelin/notebook
            - ./zeppelin/zeppelin-interpreters/interpreter.json:/zeppelin/conf/interpreter.json
        networks:
            - sparknet
            - kafkanet
            - mongodbnet



volumes:
    shared-workspace:
        name: "hadoop-distributed-file-system"
        driver: local
        
        
networks:
    kafkanet:
        external: true
    sparknet:
        external: true
    mongodbnet:
        external: true