version: "3.8"
services:


    # MongoDB Replica Set
    mongo1:
        image: mongo:4.2
        container_name: mongo1
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo-user
            MONGO_INITDB_ROOT_PASSWORD: mongo-pw
            MONGO_REPLICA_SET_NAME: rs0
        command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
        volumes:
            - rs1:/data/db
        ports:
            - "27017:27017"
        restart: always
        networks: 
            - mongodbnet

    mongo2:
        image: mongo:4.2
        container_name: mongo2
        command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
        volumes:
            - rs2:/data/db
        ports:
            - "27018:27017"
        restart: always
        networks:
            - mongodbnet
    
    mongo3:
        image: mongo:4.2
        container_name: mongo3
        command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
        volumes:
            - rs3:/data/db
        ports:
            - "27019:27017"
        restart: always
        networks:
            - mongodbnet

networks:
    mongodbnet:
        external: true
        name: mongodbnet

volumes:
    rs1:
    rs2:
    rs3: