global:
  scrape_interval: 1s
  evaluation_interval: 1s
scrape_configs:
- job_name: 'flink'
  static_configs:
    - targets: 
      - 172.25.0.20:9249
      - 172.25.0.21:9249
- job_name: 'kafka'
  static_configs:
    - targets: ['kafka1:8080', 'kafka2:8080']
